<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro", name="simple_robot">

    <!-- Properties -->
    <xacro:property name="length" value= "1.0"/>

    <!-- Base Link -->

    <link name = ""base_link">
        <visual>
            <geometry>
                <box size = "0.5 0.5 0.1"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>


    <!-- Link 1 -->
    <link name="link1">
        <visual>
            <geometry>
                <cylinder length = "${length}" radius = "0.5" />
            </geometry>
            <origin xyz = "0 0 ${length/2}" rpy = "0 0 0" />
            <material name="green"/>
        </visual>
    </link>

    <!-- Joint 1 -->
    <joint name="joint1" type="revolute">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 0.5" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.57" upper="1.57" effort="1.00" velocity="1.0"/>
    </joint>
</robot>